version: "3"

services:
  app:
    build:
      args:
        - BASE_IMAGE=nvidia/cuda:12.3.1-devel-ubuntu22.04
        - USER_NAME=user
        - PROJECT_NAME=gemma
        - PYTHON_VERSION=3.11
      context: .
      dockerfile: ./app/Dockerfile
    tty: true
    shm_size: 2gb
    volumes:
      - ../app:/home/user/gemma
    ports:
      - 5000:5000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]